# Generated by Django 2.2.4 on 2020-07-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message_id',
            new_name='on_message',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='owner',
        ),
    ]
